spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agrocrm}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:change-me-super-secret-please-change}
    expirationMinutes: 720 # 12 часов
