spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agrocrm}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:change-me-super-secret-please-change-this-is-a-very-long-secret-key-for-hs512-algorithm-that-must-be-at-least-512-bits-long}
    accessTokenExpirationMinutes: 30 # 30 минут для access token
    refreshTokenExpirationDays: 30 # 30 дней для refresh token
